In [1]:
import duckdb

df = duckdb.query("""
    SELECT *
    FROM read_parquet('../data/market_data_raw.parquet')
""").to_df()

df

,Date,Adj Close,Close,High,Low,Open,Volume,symbol,ingestion_timestamp
0,2025-10-28,28.673906,29.990000,30.350000,29.760000,29.900000,25324800,PETR4.SA,2026-04-28 18:19:19.229766-03:00
1,2025-10-29,28.702591,30.020000,30.160000,29.799999,30.090000,24854900,PETR4.SA,2026-04-28 18:19:19.229766-03:00
2,2025-10-30,28.578295,29.889999,30.160000,29.760000,29.920000,22657200,PETR4.SA,2026-04-28 18:19:19.229766-03:00
3,2025-10-31,28.444439,29.750000,30.090000,29.549999,30.000000,29516300,PETR4.SA,2026-04-28 18:19:19.229766-03:00
4,2025-11-03,28.779079,30.100000,30.469999,29.799999,29.879999,54977300,PETR4.SA,2026-04-28 18:19:19.229766-03:00
...,...,...,...,...,...,...,...,...,...
117,2026-04-22,47.017471,47.669998,47.980000,47.250000,47.639999,51063000,PETR4.SA,2026-04-28 18:19:19.229766-03:00
118,2026-04-23,47.770000,47.770000,48.080002,46.900002,47.360001,38666800,PETR4.SA,2026-04-28 18:19:19.229766-03:00
119,2026-04-24,47.160000,47.160000,47.520000,46.450001,47.500000,34880200,PETR4.SA,2026-04-28 18:19:19.229766-03:00
120,2026-04-27,47.369999,47.369999,48.169998,47.169998,47.220001,31543600,PETR4.SA,2026-04-28 18:19:19.229766-03:00
121,2026-04-28,47.520000,47.520000,48.040001,47.459999,47.650002,29331200,PETR4.SA,2026-04-28 18:19:19.229766-03:00

In [4]:
import duckdb

duckdb.query("""
    DESCRIBE
    SELECT *
             FROM read_parquet('../data/market_data_raw.parquet')
""").to_df()

           column_name               column_type null   key default extra
0                 Date                 TIMESTAMP  YES  None    None  None
1            Adj Close                    DOUBLE  YES  None    None  None
2                Close                    DOUBLE  YES  None    None  None
3                 High                    DOUBLE  YES  None    None  None
4                  Low                    DOUBLE  YES  None    None  None
5                 Open                    DOUBLE  YES  None    None  None
6               Volume                    BIGINT  YES  None    None  None
7               symbol                   VARCHAR  YES  None    None  None
8  ingestion_timestamp  TIMESTAMP WITH TIME ZONE  YES  None    None  None

In [5]:
import duckdb

df = duckdb.query("""
SELECT *
             FROM read_parquet('../data/market_data_features.parquet')
             LIMIT 20
""").to_df

df

<bound method pybind11_detail_function_record_v1_msvc_mt_mscver1944.to_df of ┌──────────┬────────────┬────────────────────┬──────────┬────────────────────────┬────────────────────┬────────────────────┬───────────────────────┐
│  symbol  │    date    │       close        │  volume  │       return_1d        │       sma_7        │       sma_30       │     volatility_7d     │
│ varchar  │    date    │       double       │  int64   │         double         │       double       │       double       │        double         │
├──────────┼────────────┼────────────────────┼──────────┼────────────────────────┼────────────────────┼────────────────────┼───────────────────────┤
│ PETR4.SA │ 2025-10-28 │ 29.989999771118164 │ 25324800 │                   NULL │ 29.989999771118164 │ 29.989999771118164 │                  NULL │
│ PETR4.SA │ 2025-10-29 │ 30.020000457763672 │ 24854900 │   0.001000356347931719 │ 30.005000114440918 │ 30.005000114440918 │                  NULL │
│ PETR4.SA │ 2025-10-30 │ 29.889999389648438 │ 22657200 │   -0.00433048188317442 │  29.96666653951009 │  29.96666653951009 │ 0.0037694718626236504 │
│ PETR4.SA │ 2025-10-31 │              29.75 │ 29516300 │  -0.004683820425132601 │  29.91249990463257 │  29.91249990463257 │ 0.0031846650781230737 │
│ PETR4.SA │ 2025-11-03 │ 30.100000381469727 │ 54977300 │    0.01176471870486484 │              29.95 │              29.95 │  0.007672102973275618 │
│ PETR4.SA │ 2025-11-04 │              30.25 │ 35035200 │   0.004983375967749781 │               30.0 │               30.0 │ 0.0068861733102151676 │
│ PETR4.SA │ 2025-11-05 │ 30.850000381469727 │ 40375900 │   0.019834723354371198 │ 30.121428625924246 │ 30.121428625924246 │  0.009615828383765589 │
│ PETR4.SA │ 2025-11-06 │ 31.010000228881836 │ 43435700 │   0.005186380727185247 │  30.26714297703334 │ 30.232500076293945 │  0.008779479175924565 │
│ PETR4.SA │ 2025-11-07 │  32.18000030517578 │ 97315600 │    0.03772976677388873 │ 30.575714383806503 │  30.44888899061415 │  0.014933503520859629 │
│ PETR4.SA │ 2025-11-10 │  32.36000061035156 │ 41064200 │   0.005593545788339593 │ 30.928571701049805 │  30.64000015258789 │  0.013763887443571708 │
│ PETR4.SA │ 2025-11-11 │  33.20000076293945 │ 68221300 │   0.025957977031656254 │   31.4214289528983 │ 30.872727480801668 │  0.012586054726792664 │
│ PETR4.SA │ 2025-11-12 │ 32.349998474121094 │ 67646400 │  -0.025602477990518624 │ 31.742857251848495 │  30.99583339691162 │   0.02022239440837222 │
│ PETR4.SA │ 2025-11-13 │   32.4900016784668 │ 38517200 │   0.004327765408016937 │ 32.062857491629465 │  31.11076941856971 │  0.020253837837510346 │
│ PETR4.SA │ 2025-11-14 │  32.70000076293945 │ 27371300 │   0.006463498726497097 │  32.32714326041086 │  31.22428594316755 │  0.019845730706032832 │
│ PETR4.SA │ 2025-11-17 │ 32.880001068115234 │ 63708200 │    0.00550459636012568 │ 32.594286237444194 │ 31.334666951497397 │  0.019837178239810686 │
│ PETR4.SA │ 2025-11-18 │   32.9900016784668 │ 26520500 │   0.003345517237778761 │ 32.710000719342915 │ 31.438125371932983 │  0.015105395410689205 │
│ PETR4.SA │ 2025-11-19 │  32.81999969482422 │ 48719300 │  -0.005153136556326432 │  32.77571487426758 │  31.51941209680894 │  0.015418501021878764 │
│ PETR4.SA │ 2025-11-21 │  32.56999969482422 │ 40869300 │  -0.007617306591243711 │  32.68571472167969 │ 31.577778074476456 │  0.011488690836946671 │
│ PETR4.SA │ 2025-11-24 │ 32.540000915527344 │ 38665600 │ -0.0009210555596548264 │  32.71285792759487 │ 31.628421381900186 │  0.005513145819503378 │
│ PETR4.SA │ 2025-11-25 │ 32.279998779296875 │ 28431100 │  -0.007990231374160883 │ 32.682857513427734 │  31.66100025177002 │  0.006147451022843136 │
└──────────┴────────────┴────────────────────┴──────────┴────────────────────────┴────────────────────┴────────────────────┴───────────────────────┘
  20 rows                                                                                                                                8 columns
>

In [6]:
import duckdb

df = duckdb.query("""
SELECT *
             FROM read_parquet('../data/market_alerts.parquet')
             LIMIT 20
""").to_df

df

<bound method pybind11_detail_function_record_v1_msvc_mt_mscver1944.to_df of ┌─────────┬──────┬───────────────┬────────────┬───────────────────┬──────────┐
│ symbol  │ date │ volatility_7d │ alert_type │ alert_description │ severity │
│ varchar │ date │    double     │  varchar   │      varchar      │ varchar  │
└─────────┴──────┴───────────────┴────────────┴───────────────────┴──────────┘
                                    0 rows
>

In [7]:
import duckdb

df = duckdb.query("""
SELECT *
             FROM read_parquet('../data/asset_ranking.parquet')
             LIMIT 20
""").to_df

df

<bound method pybind11_detail_function_record_v1_msvc_mt_mscver1944.to_df of ┌──────────┬────────────┬────────────────────┬───────────────────────┬─────────────────────┬──────────────────────┬────────────────────┬────────────────────┬──────────────┬────────────────────┬───────────────┐
│  symbol  │    date    │       close        │       return_1d       │     return_30d      │    volatility_7d     │       sma_7        │       sma_30       │ trend_signal │    score_final     │ rank_position │
│ varchar  │    date    │       double       │        double         │       double        │        double        │       double       │       double       │    int32     │       double       │     int64     │
├──────────┼────────────┼────────────────────┼───────────────────────┼─────────────────────┼──────────────────────┼────────────────────┼────────────────────┼──────────────┼────────────────────┼───────────────┤
│ PETR4.SA │ 2026-03-30 │  49.66999816894531 │ 0.0052620587398528595 │  0.3384531757482707 │ 0.017447002725247372 │  47.65285655430385 │  43.07033322652181 │            1 │ 1.3210061730230234 │             1 │
│ PETR4.SA │ 2026-03-31 │  48.66999816894531 │  -0.02013287773030803 │ 0.31932770328541715 │ 0.016350704210021987 │ 48.081427982875276 │  43.46299985249837 │            1 │ 1.3029769990753952 │             2 │
│ PETR4.SA │ 2026-02-25 │  39.56999969482422 │                   0.0 │  0.3033596475400733 │ 0.010864507779730463 │  38.22714287894113 │  36.04000034332275 │            1 │ 1.2924951397603428 │             3 │
│ PETR4.SA │ 2026-02-24 │  39.56999969482422 │    0.0253951681358211 │  0.3059406168705556 │ 0.017010891567273458 │ 37.875714438302175 │  35.73300037384033 │            1 │  1.288929725303282 │             4 │
│ PETR4.SA │ 2026-03-27 │  49.40999984741211 │  0.028946259400205898 │  0.2975314462069609 │ 0.018166375448057912 │  47.23999949863979 │  42.65166664123535 │            1 │  1.279365070758903 │             5 │
│ PETR4.SA │ 2026-03-02 │ 41.130001068115234 │   0.04576656885988961 │  0.2938030790689883 │ 0.018378806965469535 │  39.39571489606585 │ 36.878333791097006 │            1 │ 1.2754242721035187 │             6 │
│ PETR4.SA │ 2026-03-24 │  47.27000045776367 │   0.02693899003587452 │  0.2897680351905547 │  0.01785655747530513 │  46.42714255196707 │  41.57899996439616 │            1 │ 1.2719114777152496 │             7 │
│ PETR4.SA │ 2026-03-26 │  48.02000045776367 │  0.010947378058182577 │   0.285676102263714 │  0.01588506348506082 │ 46.895713806152344 │ 42.274000040690105 │            1 │ 1.2697910387786533 │             8 │
│ PETR4.SA │ 2026-04-06 │ 48.939998626708984 │  0.016407000535721306 │  0.2889122215783462 │  0.02043523859167334 │  48.60428510393415 │  44.51266644795736 │            1 │ 1.2684769829866729 │             9 │
│ PETR4.SA │ 2026-03-09 │  43.15999984741211 │  0.023719165171234735 │  0.2852887877896977 │ 0.022624492438200892 │  41.13142885480608 │  38.34333368937175 │            1 │ 1.2626642953514968 │            10 │
│ PETR4.SA │ 2026-02-26 │  39.61000061035156 │ 0.0010108899629983625 │  0.2719974754886707 │  0.00947529064222618 │  38.61571448189871 │  36.32233371734619 │            1 │ 1.2625221848464445 │            11 │
│ PETR4.SA │ 2026-02-23 │  38.59000015258789 │  0.016328651881809986 │  0.2778145423077074 │  0.01599067336071881 │  37.66285760062082 │ 35.424000358581544 │            1 │ 1.2618238689469887 │            12 │
│ PETR4.SA │ 2026-02-19 │ 37.810001373291016 │  0.016671222626417626 │   0.275641098241584 │  0.01632142486997102 │ 37.392857142857146 │  34.87300033569336 │            1 │  1.259319673371613 │            13 │
│ PETR4.SA │ 2026-03-03 │  40.95000076293945 │ -0.004376374921014059 │ 0.27808987493174864 │   0.0192701379855301 │ 39.821429116385325 │  37.17533378601074 │            1 │ 1.2588197369462186 │            14 │
│ PETR4.SA │ 2026-02-20 │ 37.970001220703125 │ 0.0042316805501396715 │  0.2728796955352377 │ 0.015179088965699644 │  37.48571450369699 │  35.14433371225993 │            1 │  1.257700606569538 │            15 │
│ PETR4.SA │ 2026-03-25 │               47.5 │   0.00486565559570562 │  0.2727760018333443 │ 0.015909814073195975 │  46.66142817905971 │  41.91833330790202 │            1 │ 1.2568661877601484 │            16 │
│ PETR4.SA │ 2026-04-02 │ 48.150001525878906 │   0.01646617292763164 │ 0.27347262039223486 │ 0.019764804168463587 │   48.3985710144043 │  44.14699986775716 │            1 │ 1.2537078162237711 │            17 │
│ PETR4.SA │ 2026-04-01 │ 47.369998931884766 │ -0.026710484610004248 │ 0.27372951549034874 │ 0.021307317832661352 │  48.27285657610212 │ 43.802333196004234 │            1 │ 1.2524221976576873 │            18 │
│ PETR4.SA │ 2026-03-11 │  44.79999923706055 │  0.043559257362952186 │ 0.26696828234628045 │  0.02184860264434094 │  42.16999980381557 │  38.92100028991699 │            1 │ 1.2451196797019395 │            19 │
│ PETR4.SA │ 2026-03-18 │               47.0 │  0.013367807624113937 │  0.2620837239966265 │  0.01799274407389871 │  45.23428562709263 │  40.34566688537598 │            1 │ 1.2440909799227278 │            20 │
└──────────┴────────────┴────────────────────┴───────────────────────┴─────────────────────┴──────────────────────┴────────────────────┴────────────────────┴──────────────┴────────────────────┴───────────────┘
  20 rows                                                                                                                                                                                            11 columns
>

In [3]:
import logging
from datetime import UTC, datetime

import duckdb


SILVER_PATH = (
    "s3://samuel-financial-data-lake/"
    "silver/**/*.parquet"
)

GOLD_BUCKET = (
    "s3://samuel-financial-data-lake/gold"
)


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
)

logger = logging.getLogger(__name__)

def create_connection():

    con = duckdb.connect()

    con.execute("INSTALL httpfs;")
    con.execute("LOAD httpfs;")

    con.execute("""
        CREATE OR REPLACE SECRET s3_secret (
            TYPE S3,
            PROVIDER credential_chain
        );
    """)

    return con

con = create_connection()

df = con.execute(f"""
DESCRIBE
SELECT *
FROM read_parquet(
    '{SILVER_PATH}',
    hive_partitioning = true
)
""").fetchdf()

print(df)

      column_name column_type null   key default extra
0          symbol     VARCHAR  YES  None    None  None
1      trade_date        DATE  YES  None    None  None
2           close      DOUBLE  YES  None    None  None
3          volume      BIGINT  YES  None    None  None
4       return_1d      DOUBLE  YES  None    None  None
5           sma_7      DOUBLE  YES  None    None  None
6          sma_30      DOUBLE  YES  None    None  None
7   volatility_7d      DOUBLE  YES  None    None  None
8  ingestion_date        DATE  YES  None    None  None